name: CI/CD Pipeline

on:
  release:
    types: [published]

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          python -m pip install build
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/supervisor_python-0.1.0-py3-none-any.whl

  Deploy:
    name: Deploy to Setonix
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-wheel

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PAWSEY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Setonix to known hosts
        run: ssh-keyscan -H setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Execute remote deployment
        run: |
          ansible-playbook -i inventory.yml deploy.yml --extra-vars "version=${{ env.TAG }}"
